[ret]
pool = "default"
bot_access_key = ""
bot_runner_access_key = ""
max_active_bot_rooms = 5

[phx]
port = 4000
ip = "127.0.0.1"
secret_key = "development-only-not-a-secret-development-only-not-a-secret"
url_host_prefix = ""
static_url_host_prefix = ""
admin_access_key = ""
secondary_url_host = ""
allow_crawlers = true

[guardian]
secret_key = "development-only-not-a-secret-development-only-not-a-secret"

[erlang]
node_cookie = "development-only-not-a-secret-development-only-not-a-secret"

[habitat]
ip = "127.0.0.1"
http_port = 9631

[oauth_google]
client_id = "foo"
client_secret = "bar"

[db]
username = "admin"
password = "admin"
hostname = "localhost"
database = "ret_dev"
template = "template0"
port = 5432
pool_size = 16

[session_lock_db]
port = 5432

[security]
content_security_policy = "default-src 'self'"
cors_origins = "*"

[pages]
insecure_ssl = "false"

[janus]
janus_port = 443

[uploads]
quota_gb = 0

[hackney]
max_connections = 50
